#pragma once
#include <imgui.h>

namespace selaura {
    enum class key_action {
        key_down,
        key_up,
        system_key_down,
        system_key_up,
        unknown
    };

    enum key : int {
        None = 0,
        NamedKey_BEGIN = 512,
        Tab = 512,
        LeftArrow,
        RightArrow,
        UpArrow,
        DownArrow,
        PageUp,
        PageDown,
        Home,
        End,
        Insert,
        Delete,
        Backspace,
        Space,
        Enter,
        Escape,
        LeftCtrl, LeftShift, LeftAlt, LeftSuper,
        RightCtrl, RightShift, RightAlt, RightSuper,
        Menu,
        NUM_0, NUM_1, NUM_2, NUM_3, NUM_4, NUM_5, NUM_6, NUM7, NUM_8, NUM_9,
        A, B, C, D, E, F, G, H, I, J,
        K, L, M, N, O, P, Q, R, S, T,
        U, V, W, X, Y, Z,
        F1, F2, F3, F4, F5, F6,
        F7, F8, F9, F10, F11, F12,
        F13, F14, F15, F16, F17, F18,
        F19, F20, F21, F22, F23, F24,
        Apostrophe,
        Comma,
        Minus,
        Period,
        Slash,
        Semicolon,
        Equal,
        LeftBracket,
        Backslash,
        RightBracket,
        GraveAccent,
        CapsLock,
        ScrollLock,
        NumLock,
        PrintScreen,
        Pause,
        Keypad0, Keypad1, Keypad2, Keypad3, Keypad4,
        Keypad5, Keypad6, Keypad7, Keypad8, Keypad9,
        KeypadDecimal,
        KeypadDivide,
        KeypadMultiply,
        KeypadSubtract,
        KeypadAdd,
        KeypadEnter,
        KeypadEqual,
        AppBack,
        AppForward,
        Oem102,

        GamepadStart,
        GamepadBack,
        GamepadFaceLeft,
        GamepadFaceRight,
        GamepadFaceUp,
        GamepadFaceDown,
        GamepadDpadLeft,
        GamepadDpadRight,
        GamepadDpadUp,
        GamepadDpadDown,
        GamepadL1,
        GamepadR1,
        GamepadL2,
        GamepadR2,
        GamepadL3,
        GamepadR3,
        GamepadLStickLeft,
        GamepadLStickRight,
        GamepadLStickUp,
        GamepadLStickDown,
        GamepadRStickLeft,
        GamepadRStickRight,
        GamepadRStickUp,
        GamepadRStickDown,

        MouseLeft, MouseRight, MouseMiddle, MouseX1, MouseX2, MouseWheelX, MouseWheelY,

        ReservedForModCtrl, ReservedForModShift, ReservedForModAlt, ReservedForModSuper,
        NamedKey_END,

        ImGuiMod_None                   = 0,
        ImGuiMod_Ctrl                   = 1 << 12,
        ImGuiMod_Shift                  = 1 << 13,
        ImGuiMod_Alt                    = 1 << 14,
        ImGuiMod_Super                  = 1 << 15,
        ImGuiMod_Mask_                  = 0xF000,

        NamedKey_COUNT         = NamedKey_END - NamedKey_BEGIN,
    };
};